package io.github.noviirna.entity;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.quarkus.hibernate.orm.panache.PanacheEntityBase;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import jakarta.validation.constraints.Null;
import jakarta.validation.constraints.Positive;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

import java.io.Serializable;

@MappedSuperclass
public abstract class BaseEntity extends PanacheEntityBase implements Serializable {

    /**
     * <b>Primary key</b, auto-generated by the database via {@link GeneratedValue}.
     * <p>
     * Marked {@link JsonProperty.Access#READ_ONLY READ_ONLY} so it's serialized into
     * every response payload, but excluded from the generated request body schema.
     * It won't appear as an input field in autogenerated Swagger for any {@code POST}/{@code PUT}
     * on entities extending {@code BaseEntity}, since the client should never be
     * the one assigning this value.
     */
    @Positive
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    @Schema(examples = "123")
    @Id
    @GeneratedValue
    public Long id;

}
