package io.github.noviirna.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.Size;

import java.io.Serial;

/**
 * Child entity in a shared-primary-key 1:1 relationship with {@code Student}
 * (see {@code docs/usecase.md} for the full before/after normalization writeup).
 * Demonstrates {@code @MapsId} as the JPA technique for eliminating a redundant
 * auto-increment key in a strict 1:1 relation, {@code Profile}'s primary key
 * is derived from, not independent of, its parent {@code Student}.
 * <p>
 * Because of the shared-key relationship, the autogenerated REST Data Panache
 * {@code add}/{@code update}/{@code delete} operations don't behave
 * correctly here, see the corresponding overrides in {@code ProfileResource} for
 * the specifics and the fixed replacements.
 */
@Entity
@Table(name = "profiles")
public class Profile extends BaseEntity {
    @Serial
    private static final long serialVersionUID = 5716107637584368332L;

    //region field
    /**
     * Overrides {@link BaseEntity#id}, unlike the default auto-incremented
     * primary key, this id is <b>not</b> independently generated. Via
     * {@link #student} below ({@code @MapsId}), it is derived directly from
     * the linked {@code Student}'s id, so {@code Profile} and {@code Student}
     * always share the same primary key value.
     * <p>
     * Still {@code READ_ONLY} like {@link BaseEntity#id}: it's set internally
     * when the {@code Profile} is created alongside its {@code Student}, never
     * assigned directly by the client.
     */
    @Positive
    @Id
    @Column(name = "student_id", nullable = false)
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    public Long id;

    @NotBlank
    @Size(max = 30, min = 5)
    public String academicLevel;
    //endregion field

    //region foreign keys
    /**
     * The parent {@code Student} this profile belongs to. {@code @MapsId} ties
     * this entity's {@link #id} to {@code student.id}, saving a {@code Profile}
     * without an associated, already-persisted {@code Student} will fail, since
     * there's no independent id to fall back on.
     * <p>
     * Hidden from JSON entirely ({@code @JsonIgnore})and not even exposed as a flat
     * id field. Access to the linked {@code Student} for aggregate operations goes
     * through {@link io.github.noviirna.dto.ProfileStudentDto ProfileStudentDto} instead
     * (see {@link io.github.noviirna.resource.ProfileResource ProfileResource}'s aggregate endpoints),
     * which carries both the {@code Profile} and {@code Student}
     * explicitly rather than relying on lazy navigation from this field.
     */
    @MapsId
    @OneToOne(cascade = {}, fetch = FetchType.LAZY)
    @JoinColumn(name = "student_id")
    @JsonIgnore
    public Student student;
    //endregion foreign keys

    //region active record query

    /**
     * Fetches a {@code Profile} together with its {@code student} relation in a
     * single query via {@code LEFT JOIN FETCH}, avoiding the N+1 query problem
     * that would otherwise occur if {@code student} were accessed lazily after
     * the fact (see {@code docs/n1-query-demo.md} for a measured side-by-side).
     */
    public static Profile findByIdWithStudent(Long id) {
        return find("FROM Profile p LEFT JOIN FETCH p.student WHERE p.id = ?1", id)
                .firstResult();
    }
    //endregion active record query
}
