package io.github.noviirna.config.oas;

import io.quarkus.smallrye.openapi.OpenApiFilter;
import org.eclipse.microprofile.openapi.models.OpenAPI;
import org.eclipse.microprofile.openapi.models.Paths;

import java.util.List;


/**
 * Post-processes the OpenAPI spec generated by REST Data Panache to correct
 * response status codes that don't match what the autogenerated endpoints
 * actually return.
 * <p>
 * REST Data Panache's default OpenAPI generation is approximate: it lists
 * status codes that never actually occur (e.g. {@code 201}/{@code 400} on a
 * {@code PUT} that only ever returns {@code 204} or {@code 404}), and omits
 * codes that do occur (e.g. {@code 404} on a single-resource {@code GET}).
 * Left as-is, Swagger ends up documenting a contract the API doesn't honor,
 * which defeats the point of having Swagger as a usable reference in the
 * first place.
 * <p>
 * Runs once at startup ({@link OpenApiFilter.RunStage#RUNTIME_STARTUP}) and
 * rewrites the {@link Paths} for every path listed in
 * {@link #REST_PANACHE_ENDPOINTS}. The actual response-shape corrections are
 * delegated to {@link OASFilterHelperPanache}, kept separate so the
 * path-matching/endpoint-list concern here stays independent from the
 * per-HTTP-method correction logic.
 * <p>
 * Only covers status codes, it does not (and can't, from a filter like this)
 * fix the missing structured error body discussed in the main README's
 * Swagger note; it just makes sure the status codes themselves are honest.
 *
 * @see <a href="https://quarkus.io/guides/openapi-swaggerui">Quarkus OpenAPI / Swagger UI guide</a>
 */
@OpenApiFilter(stages = {OpenApiFilter.RunStage.RUNTIME_STARTUP})
public class OASFilter implements org.eclipse.microprofile.openapi.OASFilter {


    /**
     * Every REST Data Panache path this filter knows how to correct.
     * Add new entities' paths here as they're introduced, anything not
     * listed is left untouched by {@link OASFilterHelperPanache#supports}.
     */
    public static final List<String> REST_PANACHE_ENDPOINTS = List.of("/course",
            "/course/{id}",
            "/enrollment",
            "/enrollment/{id}",
            "/enrollment//course/{id}",
            "/enrollment//student/{id}",
            "/profile",
            "/profile/{id}",
            "/profile/full",
            "/profile/full/{id}",
            "/student",
            "/student/{id}"
    );

    @Override
    public void filterOpenAPI(OpenAPI openAPI) {
        if (openAPI.getPaths() != null) {
            for (String panacheEndpoint : REST_PANACHE_ENDPOINTS) {
                Paths p = openAPI.getPaths();
                Paths newP = new OASFilterHelperPanache().applyCustomization(p, panacheEndpoint);
                openAPI.setPaths(newP);
            }
        }
    }


}