package io.github.noviirna.config.oas;

import org.eclipse.microprofile.openapi.OASFactory;
import org.eclipse.microprofile.openapi.models.Operation;
import org.eclipse.microprofile.openapi.models.PathItem;
import org.eclipse.microprofile.openapi.models.Paths;
import org.eclipse.microprofile.openapi.models.responses.APIResponse;

import static io.github.noviirna.config.oas.OASFilter.REST_PANACHE_ENDPOINTS;


/**
 * Holds the actual per-HTTP-method response corrections for
 * {@link OASFilter}. Split to other class so {@code OASFilter} only has to own the list
 * of paths to correct, while the "what's wrong with each method's documented
 * responses, and how to fix it" logic lives here and can grow independently
 * (e.g. supporting POST, or different correction rules per entity, without
 * touching {@code OASFilter} itself).
 */
public class OASFilterHelperPanache {


    /**
     * Whether this path is one {@link OASFilter} is configured to correct.
     * Paths not in {@link OASFilter#REST_PANACHE_ENDPOINTS} are left as the
     * REST Data Panache default (possibly inaccurate, but out of scope for
     * this filter to touch.)
     */
    boolean supports(String path) {
        return REST_PANACHE_ENDPOINTS.stream().anyMatch(e -> e.equals(path));
    }

    /**
     * Routes to the correction logic appropriate for the path's shape:
     * collection paths (e.g. {@code /course}) only need their {@code GET}
     * corrected, while single-resource paths (e.g. {@code /course/{id}})
     * need {@code GET}, {@code PUT}, and {@code DELETE} all corrected, since
     * REST Data Panache documents each of those differently per path shape.
     */
    Paths applyCustomization(Paths paths, String path) {
        if (!supports(path)) return paths;

        boolean hasPathParam = path.contains("{") && path.contains("}");

        if (hasPathParam)
            return processPathWithParam(paths, path);
        else
            return processPaths(paths, path);
    }

    private Paths processPaths(Paths originPaths, String endpoint) {
        PathItem item = originPaths.getPathItem(endpoint);
        if (item == null) return originPaths;

        item.setPOST(adjustPostApiResponse(item));
        originPaths.removePathItem(endpoint);
        originPaths.addPathItem(endpoint, item);

        return originPaths;
    }

    private Paths processPathWithParam(Paths originPaths, String endpoint) {
        PathItem item = originPaths.getPathItem(endpoint);
        if (item == null) return originPaths;

        item.setPUT(adjustPutApiResponse(item));
        item.setDELETE(adjustDeleteApiResponse(item));
        item.setGET(adjustGetApiResponseSingle(item));
        item.setPOST(adjustPostApiResponse(item));

        originPaths.removePathItem(endpoint);
        originPaths.addPathItem(endpoint, item);

        return originPaths;
    }

    /**
     * Removes {@code 200}, {@code 201}, which the autogenerated {@code PUT}
     * never returns either; it only ever returns {@code 204} (updated),
     * {@code 404} (not found), and {@code 500} (internal server error).
     * Adds those as the documented responses.
     */
    private Operation adjustPutApiResponse(PathItem pi) {
        Operation origin = pi.getPUT();
        if (origin == null) return null;

        origin.getResponses().removeAPIResponse("200");
        origin.getResponses().removeAPIResponse("201");

        origin.getResponses().addAPIResponse("204", getAPIResponseUpdateSuccess());
        origin.getResponses().addAPIResponse("404", getAPIResponseNotFound());
        origin.getResponses().addAPIResponse("500", getAPIResponseInternalServerError());


        return origin;
    }


    /**
     * Adds the missing {@code 404} to a single-resource {@code GET}
     * (e.g. {@code /course/{id}}), the autogenerated spec doesn't document
     * it, even though requesting a non-existent id does return one.
     */
    private Operation adjustGetApiResponseSingle(PathItem pi) {
        Operation op = pi.getGET();

        if (op == null) return null;

        op.getResponses().addAPIResponse("404", getAPIResponseNotFound());

        return op;
    }


    private Operation adjustPostApiResponse(PathItem pi) {
        Operation op = pi.getPOST();

        if (op == null) return null;

        op.getResponses().removeAPIResponse("200");

        op.getResponses().addAPIResponse("201", getApiResponseCreated());
        op.getResponses().addAPIResponse("500", getAPIResponseInternalServerError());
        return op;
    }

    /**
     * Removes {@code 201}, never returned by {@code DELETE} and adds
     * {@code 204} (deleted), {@code 404} (not found), and {@code } (conflicted) instead. Also sets
     * {@code 204} as the default response, since that's the expected outcome
     * for a delete call that doesn't hit either documented edge case.
     */
    private Operation adjustDeleteApiResponse(PathItem pi) {
        Operation op = pi.getDELETE();

        if (op == null) return null;

        op.getResponses().removeAPIResponse("200");
        op.getResponses().removeAPIResponse("201");

        op.getResponses().addAPIResponse("204", getAPIResponseUpdateSuccess());
        op.getResponses().addAPIResponse("404", getAPIResponseNotFound());
        op.getResponses().addAPIResponse("409", getAPIResponseConflicted());


        op.getResponses().setDefaultValue(getAPIResponseUpdateSuccess());

        return op;
    }

    private APIResponse getApiResponseCreated() {
        return OASFactory.createAPIResponse()
                .description("Created");
    }


    private APIResponse getAPIResponseUpdateSuccess() {
        return OASFactory.createAPIResponse()
                .description("Successfully update data");
    }

    private APIResponse getAPIResponseNotFound() {
        return OASFactory.createAPIResponse()
                .description("Not Found");
    }

    private APIResponse getAPIResponseConflicted() {
        return OASFactory.createAPIResponse()
                .description("Conflict");
    }

    private APIResponse getAPIResponseInternalServerError() {
        return OASFactory.createAPIResponse()
                .description("Error: Internal Server Error");
    }


}
