# Set the JSON serialization deserialization properties
quarkus.jackson.serialization-inclusion=non-empty
quarkus.jackson.fail-on-unknown-properties=false
quarkus.jackson.property-naming-strategy=SNAKE_CASE

# Set the smallrye openapi property naming strategy to snake case, sync with the Jackson for JSON serialization and deserialization
mp.openapi.extensions.smallrye.property-naming-strategy=com.fasterxml.jackson.databind.PropertyNamingStrategies$SnakeCaseStrategy

# Use in-memory database for testing and development purposes (add prefix %dev to make it only active in dev mode)
%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.datasource.username=admin
%dev.quarkus.datasource.password=admin
%dev.quarkus.datasource.jdbc.url=jdbc:h2:mem:default

# Use camelCase to under_score naming strategy for hibernate orm
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# Use drop and create (drop and create new schema on startup) strategy just for demonstration purposes.
# AVOID using this on production environment as it will lead to data loss.
# In production environment, consider using 'validate' or 'update' strategy instead.
# (add prefix %dev to make it only active in dev mode)
%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create

# enable hibernate sql logging for testing and development purposes (add prefix %dev to make it only active in dev mode)
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.hibernate-orm.format-sql=true
%dev.quarkus.hibernate-orm.validate-in-dev-mode=false

# enable swagger ui for testing and development purposes
# swagger -> http://localhost:8080/q/dev-ui/quarkus-smallrye-openapi/swagger-ui
# (add prefix %dev to make it only active in dev mode)
%dev.quarkus.swagger-ui.always-include=true

# enable hibernate orm dev ui for testing and development purposes
# (add prefix %dev to make it only active in dev mode)
%dev.quarkus.hibernate-orm.dev-ui.allow-hql=true

# Enable bind parameter logging
# (add prefix %dev to make it only active in dev mode)
%dev.quarkus.hibernate-orm.log.bind-parameters=true

# Set the minimum log level to TRACE to see the parameters of SQL queries
# (add prefix %dev to make it only active in dev mode)
%dev.quarkus.log.category."org.hibernate.type.descriptor.sql.BasicBinder".level=TRACE
%dev.quarkus.log.min-level=TRACE


