package io.github.noviirna.resource;

import io.github.noviirna.entity.Course;
import io.quarkus.hibernate.orm.rest.data.panache.PanacheEntityResource;
import io.quarkus.rest.data.panache.MethodProperties;
import io.quarkus.rest.data.panache.ResourceProperties;


@ResourceProperties
public interface CourseResource extends PanacheEntityResource<Course, Long> {

    // region hidden endpoints

    /**
     * <b>Disabled</b><br>out of scope for this template, and risky to leave exposed.
     * On large tables, an unbounded {@code COUNT} can be expensive and tie up a
     * connection thread for the duration of the scan.
     * <p>
     * If you need a count, query it directly via your DBMS instead of exposing it as an API.
     */
    @Override
    @MethodProperties(exposed = false)
    long count();

    /**
     * Overridden purely to attach this javadoc.
     * The behavior is otherwise identical to the default autogenerated {@code delete()}.
     * <p>
     * Works as-is <b>only if no {@code Enrollment} rows reference this course</b>,
     * {@code Course} and {@code Enrollment} aren't a shared-primary-key relationship
     * like {@code Student}/{@code Profile}, so this isn't disabled outright, but the
     * constraint still applies via a regular foreign key.
     * <p>
     * If any {@code Enrollment} still references this {@code Course}, deleting it
     * fails with an unhandled {@code ConstraintViolationException} (FK violation),
     * surfacing as a raw {@code 500} rather than a clean client error, no exception
     * mapper is provided in this template (out of scope), and this can't be
     * documented as a conditional response in the generated Swagger schema either.
     * <p>
     * To delete a {@code Course} that still has enrollments, remove the related
     * {@code Enrollment} rows first.
     */
    @Override
    boolean delete(Long id);
    // endregion hidden endpoints

}
