package io.github.noviirna.resource;

import io.github.noviirna.dto.ProfileStudentDto;
import io.github.noviirna.entity.Profile;
import io.github.noviirna.entity.Student;
import io.quarkus.hibernate.orm.rest.data.panache.PanacheEntityResource;
import io.quarkus.rest.data.panache.MethodProperties;
import io.quarkus.rest.data.panache.ResourceProperties;
import jakarta.transaction.Transactional;
import jakarta.validation.Valid;
import jakarta.ws.rs.*;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import org.eclipse.microprofile.openapi.annotations.Operation;
import org.eclipse.microprofile.openapi.annotations.parameters.RequestBody;

import java.net.URI;


@ResourceProperties
public interface ProfileResource extends PanacheEntityResource<Profile, Long> {

    // region hidden endpoints

    /**
     * <b>Disabled</b><br>
     * See {@linkplain CourseResource#count()} for rationale.<p>
     * Applied consistently across all entities in this template.
     */
    @Override
    @MethodProperties(exposed = false)
    @Operation(hidden = true)
    long count();

    /**
     * <b>Disabled</b><br>
     * The autogenerated API for INSERT operation doesn't correctly handle
     * a child entity that share its PK with the parent entity via {@code MapsId}.
     * <p>
     * The generated endpoint tries to persist {@code Profile} with an auto-assigned ID,
     * which conflicts with the derived (shared) primary key strategy.
     * <p>
     * Please use the fixed custom method below {@link ProfileResource#addFixed(Long, Profile)}
     */
    @Override
    @MethodProperties(exposed = false)
    @Operation(hidden = true)
    Profile add(Profile entity);

    /**
     * <b>Disabled</b><br>
     * The autogenerated UPDATE operation doesn't account for a primary key
     * that's derived from the parent via {@code @MapsId}.
     * Same root cause as {@link ProfileResource#add(Profile)}.
     * <p>
     * Please use the fixed custom method below {@link ProfileResource#updateFixed(Long, Profile)}
     */
    @MethodProperties(exposed = false)
    @Operation(hidden = true)
    Profile update(Long id, Profile entity);
    // endregion hidden endpoints

    //region custom endpoint

    /**
     * Fixed replacement (option 1 of 2) for the disabled autogenerated {@code POST}
     * ({@link ProfileResource#add}). Use this when the {@code Student} <b>already
     * exists</b> and you're just attaching a {@code Profile} to it, {@code id} is
     * the existing student's id. For creating both together from scratch, see
     * {@link #addAggregate} instead.
     * <p>
     * Since {@code Profile.id} is derived from {@code Student.id} via {@code @MapsId},
     * the two will share the same value once persisted.
     * <p>
     * Uses {@link jakarta.persistence.EntityManager#getReference} rather than a
     * lookup like {@code findById}, only the {@code Student}'s id is needed to
     * populate the foreign key, so there's no reason to issue an extra
     * {@code SELECT} against the {@code students} table just to discard the result.
     * <p>
     * <b>Known limitation:</b> {@code getReference} doesn't validate that the
     * {@code Student} actually exists, it only builds a proxy. If {@code id}
     * doesn't correspond to a real {@code Student}, the failure surfaces later, at
     * {@code persist()}, as an unhandled {@code ConstraintViolationException} (FK
     * violation), which currently returns a raw {@code 500} instead of a clean
     * client-facing {@code 400}/{@code 404}. No exception mapper is provided in
     * this template, out of scope for what this repo demonstrates.
     */
    @SuppressWarnings("unused")
    @POST
    @Path("/{id : \\d+}")
    @Transactional
    default Response addFixed(@PathParam("id") Long id, @Valid Profile profile) {
        if (id == null || profile == null)
            throw new WebApplicationException(Response.status(Response.Status.BAD_REQUEST).build());
        profile.student = Profile.getEntityManager().getReference(Student.class, id);
        profile.persist();
        return Response.created(URI.create("/profile/" + profile.id))
                .entity(profile).build();
    }


    /**
     * Fixed replacement for the disabled autogenerated {@code PUT} ({@link ProfileResource#update}).
     * Same shared-primary-key rationale as {@link #addFixed}: {@code id} is the
     * <b>student's</b> id, and {@code getReference} is used instead of a lookup
     * since only the id is needed to re-link the foreign key, not the full
     * {@code Student} entity.
     * <p>
     * Same known limitation as {@link #addFixed}: an invalid {@code id} surfaces as
     * a raw {@code 500} from {@code ConstraintViolationException}, not a handled
     * client error, no exception mapper is included in this template.
     */
    @SuppressWarnings("unused")
    @PUT
    @Path("/{id : \\d+}")
    @Transactional
    default Response updateFixed(@PathParam("id") Long id, @Valid Profile profile) {
        if (id == null || profile == null)
            throw new WebApplicationException(Response.status(Response.Status.NOT_FOUND).build());
        profile.id = id;
        profile.student = Profile.getEntityManager().getReference(Student.class, id);
        Profile.getEntityManager().merge(profile);
        return Response.noContent().build();
    }


    /**
     * Optimized counterpart to {@link #getAggregateDemoN1Problem}.
     * It fetches {@code Profile} and its {@code student} relation in a single query via
     * {@code LEFT JOIN FETCH}, avoiding the N+1 query problem entirely.
     * See {@link #getAggregateDemoN1Problem} for what happens without it.
     *
     * @param id the {@code Profile} id
     * @return the {@code Profile} and its linked {@code Student}, fetched in one query
     */
    @SuppressWarnings("unused")
    @Transactional
    @GET
    @Path("/full/{id : \\d+}")
    @Produces(MediaType.APPLICATION_JSON)
    default ProfileStudentDto getAggregate(@PathParam("id") long id) {
        Profile p = Profile.findByIdWithStudent(id);
        if (p == null) throw new WebApplicationException(404);
        return new ProfileStudentDto(p, p.student);
    }


    /**
     * Demonstrates how lazy loading silently leads to the N+1 query problem.
     * <p>
     * {@code Profile.findById} only loads the {@code Profile} row, and {@code student}
     * stays an uninitialized lazy proxy. Then, when {@code ProfileStudentDto} is built and
     * later serialized to JSON, accessing {@code p.student} triggers Hibernate to
     * fire a <i>separate</i> query to fetch the {@code Student} row, on top of the
     * one that already fetched {@code Profile}.
     * <p>
     * That's why it's recommended to:
     * <ul>
     *     <li>return a DTO instead of the entity directly, so what gets serialized
     *     and what lazy relations get triggered stays under your control.</li>
     *     <li>use a join fetch (see {@link #getAggregate}) to retrieve related
     *     entities in a single query instead of triggering lazy loads one at a time.</li>
     * </ul>
     * <p>
     * Compare against {@link #getAggregate}, which returns the identical
     * {@code ProfileStudentDto} shape in one query instead of two.
     * <p>
     * This endpoint is for <u>demonstration only</u>, it is NOT RECOMMENDED for production use
     *
     * @param id the {@code Profile} id
     * @return the {@code Profile} and its linked {@code Student}, fetched via a lazily-triggered second query
     */
    @SuppressWarnings("unused")
    @GET
    @Path("/full/{id : \\d+}/demo/n+1problem")
    @Produces("application/json")
    default ProfileStudentDto getAggregateDemoN1Problem(@PathParam("id") long id) {
        Profile p = Profile.findById(id);
        if (p == null) throw new WebApplicationException(404);
        return new ProfileStudentDto(p, p.student);
    }


    /**
     * Fixed replacement (option 2 of 2) for the disabled autogenerated {@code POST}
     * ({@link ProfileResource#add}). Use this when the {@code Student}
     * <b>doesn't exist yet</b>. Both {@code Student} and {@code Profile} are
     * created together in one request/transaction. If the {@code Student} already
     * exists, use {@link #addFixed} instead.
     * <p>
     * Order matters: {@code Student} is persisted first so it has an assigned id,
     * which {@code Profile} then derives its own id from via the {@code @MapsId}
     * relation before being persisted itself.
     * <p>
     * Preferred over manually inserting {@code Student} and {@code Profile}
     * separately through generic endpoints: this keeps the 1:1 shared-primary-key
     * relationship enforced atomically, so the two rows can't end up created in a
     * partial or inconsistent state.
     *
     * @param request carries both the {@code Student} and {@code Profile} payloads
     *                to create together
     * @return the persisted {@code Student} and {@code Profile}, both now sharing
     */
    @SuppressWarnings("unused")
    @Transactional
    @POST
    @Path("/full")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    default Response addAggregate(@RequestBody @Valid ProfileStudentDto request) {
        Student s = request.student();
        s.persist();

        Profile p = request.profile();
        p.student = s;
        p.persist();
        ProfileStudentDto dto = new ProfileStudentDto(p, s);
        return Response.created(URI.create("/profile/full"))
                .entity(dto).build();
    }

    /**
     * Deletes both {@code Profile} and {@code Student} together in a single request.
     * Not strictly the only way to remove this pair, you could call delete on
     * {@code Profile} and {@code Student} separately through their own endpoints.
     * But doing it here in one transaction avoids two round trips and keeps the
     * delete atomic, instead of risking a state where one side is removed and the
     * other isn't because the second call failed or was never made.
     * <p>
     * Preferred over manually delete {@code Student} and {@code Profile}
     * separately through generic endpoints: this keeps the 1:1 shared-primary-key
     * relationship enforced atomically, so the two rows can't end up created in a
     * partial or inconsistent state.
     *
     * @param id the shared {@code Profile}/{@code Student} id
     * @return {@code 204 No Content} if deleted, {@code 404 Not Found} if no
     * {@code Profile} with that id existed
     */
    @Transactional
    @DELETE
    @Path("/full/{id : \\d+}")
    @Produces(MediaType.APPLICATION_JSON)
    default Response deleteAggregate(@PathParam("id") long id) {
        return Response
                .status(Profile.deleteById(id) ?
                        Student.deleteById(id) ? Response.Status.NO_CONTENT : Response.Status.NOT_FOUND
                        : Response.Status.NOT_FOUND)
                .build();
    }
    //endregion custom endpoint


}
