package io.github.noviirna.resource.panacheentity.integration;

import com.fasterxml.jackson.core.JsonProcessingException;
import io.github.noviirna.dto.ProfileStudentDto;
import io.github.noviirna.entity.BaseEntity;
import io.github.noviirna.entity.Profile;
import io.github.noviirna.resource.panacheentity.RestPanacheTest;
import io.github.noviirna.resource.panacheentity.RestPanacheTestFactory;
import io.github.noviirna.resource.panacheentity.factory.ProfileFactory;
import io.quarkus.test.junit.QuarkusTest;
import io.restassured.http.ContentType;
import jakarta.inject.Inject;
import org.hamcrest.Matchers;
import org.jboss.resteasy.reactive.RestResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import static io.restassured.RestAssured.given;

@QuarkusTest
class ProfileIT extends RestPanacheTest<Profile> {

    @Inject
    ProfileFactory profileFactory;

    @Override
    protected RestPanacheTestFactory<Profile> factory() {
        return profileFactory;
    }

    private static final String PATH_AGGREGATE = "/full";
    private static final String BODY_PATH_STUDENT_ID = "student.id";
    private static final String BODY_PATH_PROFILE_ID = "profile.id";

    @Test
    protected void testPost_whileApiIsDisabled_405() throws JsonProcessingException {
        BaseEntity p = factory().insertEntity();
        given()
                .contentType(ContentType.JSON)
                .body(objectMapper.writeValueAsString(p))
                .when()
                .post(factory().getPath())
                .then()
                .assertThat()
                .statusCode(RestResponse.StatusCode.METHOD_NOT_ALLOWED);
    }


    @Disabled("Profile doesn't support panache autogenerated POST API, skip this test")
    @Override
    @Test
    protected void testPost_isSuccess_201() {
    }

    @Disabled("Profile doesn't support panache autogenerated POST API, skip this test")
    @Override
    @Test
    protected void testPost_invalidParameter_400() {
    }

    @Test
    protected void testPostAggregate_isSuccess_201() throws JsonProcessingException {
        Profile p = factory().insertEntity();
        factory().delete(p);

        given()
                .contentType(ContentType.JSON)
                .body(objectMapper.writeValueAsString(new ProfileStudentDto(p, p.student)))
                .when()
                .post(factory().getPath() + PATH_AGGREGATE)
                .then()
                .assertThat()
                .statusCode(RestResponse.StatusCode.CREATED);
    }

    @Test
    protected void testPostAggregate_invalidParameter_400() {
        given()
                .contentType(ContentType.JSON)
                .body("{}")
                .when()
                .post(factory().getPath() + PATH_AGGREGATE)
                .then()
                .assertThat()
                .statusCode(RestResponse.StatusCode.BAD_REQUEST);
    }

    @Test
    protected void testHardDeleteAggregate_success_204() {
        BaseEntity p = factory().insertEntity();
        given()
                .contentType(ContentType.JSON)
                .pathParam(FIELDNAME_ID, p.id)
                .when()
                .delete(factory().getPath() + PATH_AGGREGATE + PATHPARAM_ID)
                .then()
                .assertThat()
                .statusCode(RestResponse.StatusCode.NO_CONTENT);
    }

    @Test
    protected void testHardDeleteAggregate_isNotFound_404() {
        given()
                .contentType(ContentType.JSON)
                .pathParam(FIELDNAME_ID, VALUE_ID)
                .when()
                .delete(factory().getPath() + PATH_AGGREGATE + PATHPARAM_ID)
                .then()
                .assertThat()
                .statusCode(RestResponse.StatusCode.NOT_FOUND);
    }

    @ParameterizedTest
    @ValueSource(strings = {"", "/demo/n+1problem"})
    protected void testFindByIdAggregate_isExists_200(String additionalPath) {
        BaseEntity p = factory().insertEntity();
        given()
                .when()
                .pathParam(FIELDNAME_ID, p.id.intValue())
                .urlEncodingEnabled(false)
                .get(factory().getPath() + PATH_AGGREGATE + PATHPARAM_ID + additionalPath)
                .then()
                .statusCode(RestResponse.StatusCode.OK)
                .body(
                        BODY_PATH_STUDENT_ID, Matchers.notNullValue(),
                        BODY_PATH_STUDENT_ID, Matchers.is(p.id.intValue()),
                        BODY_PATH_PROFILE_ID, Matchers.notNullValue(),
                        BODY_PATH_PROFILE_ID, Matchers.is(p.id.intValue())
                )
        ;
    }

    @ParameterizedTest
    @ValueSource(strings = {"", "/demo/n+1problem"})
    protected void testFindByIdAggregate_isNotFound_404(String additionalPath) {
        given()
                .when()
                .pathParam(FIELDNAME_ID, VALUE_ID)
                .urlEncodingEnabled(false)
                .get(factory().getPath() + PATH_AGGREGATE + PATHPARAM_ID + additionalPath)
                .then().assertThat()
                .statusCode(RestResponse.StatusCode.NOT_FOUND);
    }

}