package io.github.noviirna.resource.panacheentity.integration;

import io.github.noviirna.entity.Student;
import io.github.noviirna.resource.panacheentity.RestPanacheTest;
import io.github.noviirna.resource.panacheentity.RestPanacheTestFactory;
import io.github.noviirna.resource.panacheentity.factory.StudentFactory;
import io.quarkus.test.junit.QuarkusTest;
import io.restassured.http.ContentType;
import jakarta.inject.Inject;
import org.jboss.resteasy.reactive.RestResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import static io.restassured.RestAssured.given;

@QuarkusTest
class StudentIT extends RestPanacheTest<Student> {

    @Inject
    StudentFactory studentFactory;

    @Override
    protected RestPanacheTestFactory<Student> factory() {
        return studentFactory;
    }

    @Disabled("Student doesn't support panache autogenerated DELETE API, skip this test")
    @Override
    @Test
    protected void testHardDelete_success_204() {
    }

    @Disabled("Student doesn't support panache autogenerated DELETE API, skip this test")
    @Override
    @Test
    protected void testHardDelete_isNotFound_404() {
    }

    @Test
    protected void testHardDelete_whileApiIsDisabled_405() {
        given()
                .contentType(ContentType.JSON)
                .pathParam(FIELDNAME_ID, VALUE_ID)
                .when()
                .delete(factory().getPath() + PATHPARAM_ID)
                .then()
                .assertThat()
                .statusCode(RestResponse.StatusCode.METHOD_NOT_ALLOWED);
    }

}