package io.github.noviirna.resource.panacheentity.integration;

import io.github.noviirna.entity.Student;
import io.github.noviirna.resource.panacheentity.RestPanacheTest;
import io.github.noviirna.resource.panacheentity.RestPanacheTestFactory;
import io.github.noviirna.resource.panacheentity.factory.StudentFactory;
import io.quarkus.test.junit.QuarkusTest;
import io.restassured.http.ContentType;
import jakarta.inject.Inject;
import org.jboss.resteasy.reactive.RestResponse;
import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.Test;

import static io.restassured.RestAssured.given;

@QuarkusTest
class StudentIT extends RestPanacheTest<Student> {

    @Inject
    StudentFactory studentFactory;

    @Override
    protected RestPanacheTestFactory<Student> factory() {
        return studentFactory;
    }

    @Override
    @Test
    protected void testPost_whileApiIsDisabled_405() {
        Assumptions.assumeTrue(
                false,
                "Student support post, skip this test");
    }

    @Override
    @Test
    protected void testHardDelete_success_204() {
        Assumptions.assumeTrue(
                false,
                "Student doesnt support autogenerated delete, skip this test");
    }

    @Override
    @Test
    protected void testHardDelete_isNotFound_404() {
        Assumptions.assumeTrue(
                false,
                "Student doesnt support autogenerated delete, skip this test");
    }

    @Test
    protected void testHardDelete_whileApiIsDisabled_405() {
        given()
                .contentType(ContentType.JSON)
                .pathParam("id", 1l)
                .when()
                .delete(factory().getPath() + "/{id}")
                .then()
                .assertThat()
                .statusCode(RestResponse.StatusCode.METHOD_NOT_ALLOWED);
    }

}